authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
name = "PolynomialOperators"
uuid = "88d0e30e-9bf2-11e8-110a-078b1f1acb7c"
version = "0.1.0"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
